#!/bin/bash

# Script to generate perturbed results with 0.05 injection rate

set -e

cd "$(dirname "$0")"

MODELS="gpt-4o-mini-2024-07-18-FC gpt-4.1-mini-2025-04-14-FC"
TEST_CATEGORY="web_search"
PERTURBED_RESULT_DIR="result_perturbed_new"
PERTURBED_SCORE_DIR="score_perturbed_new"
PERTURBATION_RATE="0.05"

echo "=========================================="
echo "Generating PERTURBED Results (0.05 rate)"
echo "=========================================="
echo ""

# Backup current .env
if [ -f .env ]; then
    cp .env .env.backup2
    echo "✅ Backed up .env to .env.backup2"
fi

# Function to update .env perturbation settings
update_env_perturbation() {
    local enable=$1
    local rate=$2
    
    # Create a temporary file without perturbation settings
    grep -v '^BFCL_ENABLE_RANDOM_INSERTION=' .env | \
    grep -v '^BFCL_RANDOM_INSERTION_RATE=' | \
    grep -v '^BFCL_RANDOM_INSERTION_TEXT_POOL=' | \
    grep -v '^# Perturbation settings' > .env.tmp || true
    
    # Add new settings
    echo "" >> .env.tmp
    echo "# Perturbation settings (auto-generated by generate_perturbed script)" >> .env.tmp
    echo "BFCL_ENABLE_RANDOM_INSERTION=$enable" >> .env.tmp
    echo "BFCL_RANDOM_INSERTION_RATE=$rate" >> .env.tmp
    echo "BFCL_RANDOM_INSERTION_TEXT_POOL=\"ADVERTISEMENT,[Sponsored],[Promoted],[Click here],[Learn more],...,***\"" >> .env.tmp
    
    # Replace .env with the updated version
    mv .env.tmp .env
    
    echo "✅ Updated .env: BFCL_ENABLE_RANDOM_INSERTION=$enable, BFCL_RANDOM_INSERTION_RATE=$rate"
}

# Enable perturbation
update_env_perturbation "true" "$PERTURBATION_RATE"

# Clean up old perturbed results if they exist
if [ -d "$PERTURBED_RESULT_DIR" ]; then
    echo "🗑️  Removing old perturbed results..."
    rm -rf "$PERTURBED_RESULT_DIR"
fi

# Generate perturbed results
echo "🔄 Generating perturbed results..."
for model in $MODELS; do
    echo "  Generating for $model..."
    bfcl generate \
        --model "$model" \
        --test-category "$TEST_CATEGORY" \
        --num-threads 4 \
        --result-dir "$PERTURBED_RESULT_DIR" \
        --allow-overwrite || {
        echo "❌ Generation failed for $model"
        exit 1
    }
done

echo ""
echo "✅ Perturbed generation complete!"
echo ""

# Evaluate perturbed results
echo "=========================================="
echo "Evaluating PERTURBED results"
echo "=========================================="
echo ""

for model in $MODELS; do
    echo "🦍 Model: $model (perturbed)"
    bfcl evaluate \
        --model "$model" \
        --test-category "$TEST_CATEGORY" \
        --result-dir "$PERTURBED_RESULT_DIR" \
        --score-dir "$PERTURBED_SCORE_DIR" \
        --partial-eval || {
        echo "⚠️  Evaluation failed for $model"
    }
    echo ""
done

echo "✅ Perturbed evaluation complete!"
echo ""

# Display comparison
echo "=========================================="
echo "Results Comparison"
echo "=========================================="
echo ""

echo "UNPERTURBED Results:"
for model in $MODELS; do
    if [ -f "score_baseline/$model/agentic/BFCL_v4_web_search_base_score.json" ]; then
        base_acc=$(python3 -c "import json; f=open('score_baseline/$model/agentic/BFCL_v4_web_search_base_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}% ({d['correct_count']}/{d['total_count']})\")" 2>/dev/null || echo "N/A")
        no_snippet_acc=$(python3 -c "import json; f=open('score_baseline/$model/agentic/BFCL_v4_web_search_no_snippet_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}% ({d['correct_count']}/{d['total_count']})\")" 2>/dev/null || echo "N/A")
        echo "  $model:"
        echo "    web_search_base: $base_acc"
        echo "    web_search_no_snippet: $no_snippet_acc"
    fi
done

echo ""
echo "PERTURBED Results (rate: $PERTURBATION_RATE):"
for model in $MODELS; do
    if [ -f "$PERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_base_score.json" ]; then
        base_acc=$(python3 -c "import json; f=open('$PERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_base_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}% ({d['correct_count']}/{d['total_count']})\")" 2>/dev/null || echo "N/A")
        no_snippet_acc=$(python3 -c "import json; f=open('$PERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_no_snippet_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}% ({d['correct_count']}/{d['total_count']})\")" 2>/dev/null || echo "N/A")
        echo "  $model:"
        echo "    web_search_base: $base_acc"
        echo "    web_search_no_snippet: $no_snippet_acc"
    fi
done

echo ""
echo "=========================================="
echo "✅ All done! Results saved in:"
echo "   - Perturbed: $PERTURBED_RESULT_DIR, $PERTURBED_SCORE_DIR"
echo "=========================================="

