#!/bin/bash

# Script to regenerate results with proper perturbation comparison
# This ensures both conditions are run sequentially with the same web search results

set -e

cd "$(dirname "$0")"

MODELS="gpt-4o-mini-2024-07-18-FC gpt-4.1-mini-2025-04-14-FC"
TEST_CATEGORY="web_search"
UNPERTURBED_RESULT_DIR="result_baseline"
PERTURBED_RESULT_DIR="result_perturbed_new"
UNPERTURBED_SCORE_DIR="score_baseline"
PERTURBED_SCORE_DIR="score_perturbed_new"
PERTURBATION_RATE="0.05"

echo "=========================================="
echo "Regenerating Results with Proper Comparison"
echo "=========================================="
echo ""
echo "⚠️  This will generate results for 2 models × 2 test categories"
echo "   (~400 API calls per condition, ~800 total)"
echo ""

# Backup current .env
if [ -f .env ]; then
    cp .env .env.backup
    echo "✅ Backed up .env to .env.backup"
fi

# Function to update .env perturbation settings
update_env_perturbation() {
    local enable=$1
    local rate=$2
    
    # Create a temporary file without perturbation settings
    grep -v '^BFCL_ENABLE_RANDOM_INSERTION=' .env | \
    grep -v '^BFCL_RANDOM_INSERTION_RATE=' | \
    grep -v '^BFCL_RANDOM_INSERTION_TEXT_POOL=' | \
    grep -v '^# Perturbation settings' > .env.tmp || true
    
    # Add new settings
    echo "" >> .env.tmp
    echo "# Perturbation settings (auto-generated by regenerate script)" >> .env.tmp
    echo "BFCL_ENABLE_RANDOM_INSERTION=$enable" >> .env.tmp
    echo "BFCL_RANDOM_INSERTION_RATE=$rate" >> .env.tmp
    echo "BFCL_RANDOM_INSERTION_TEXT_POOL=\"ADVERTISEMENT,[Sponsored],[Promoted],[Click here],[Learn more],...,***\"" >> .env.tmp
    
    # Replace .env with the updated version
    mv .env.tmp .env
    
    echo "✅ Updated .env: BFCL_ENABLE_RANDOM_INSERTION=$enable, BFCL_RANDOM_INSERTION_RATE=$rate"
}

# Step 1: Generate UNPERTURBED results
echo "=========================================="
echo "Step 1: Generating UNPERTURBED results"
echo "=========================================="
echo ""

update_env_perturbation "false" "0.05"

# Clean up old baseline results if they exist
if [ -d "$UNPERTURBED_RESULT_DIR" ]; then
    echo "🗑️  Removing old baseline results..."
    rm -rf "$UNPERTURBED_RESULT_DIR"
fi

echo "🔄 Generating unperturbed results..."
for model in $MODELS; do
    echo "  Generating for $model..."
    bfcl generate \
        --model "$model" \
        --test-category "$TEST_CATEGORY" \
        --num-threads 4 \
        --result-dir "$UNPERTURBED_RESULT_DIR" \
        --allow-overwrite || {
        echo "❌ Generation failed for $model"
        exit 1
    }
done

echo ""
echo "✅ Unperturbed generation complete!"
echo ""

# Step 2: Evaluate UNPERTURBED results
echo "=========================================="
echo "Step 2: Evaluating UNPERTURBED results"
echo "=========================================="
echo ""

for model in $MODELS; do
    echo "🦍 Model: $model (unperturbed)"
    bfcl evaluate \
        --model "$model" \
        --test-category "$TEST_CATEGORY" \
        --result-dir "$UNPERTURBED_RESULT_DIR" \
        --score-dir "$UNPERTURBED_SCORE_DIR" || {
        echo "⚠️  Evaluation failed for $model"
    }
    echo ""
done

echo "✅ Unperturbed evaluation complete!"
echo ""

# Step 3: Generate PERTURBED results
echo "=========================================="
echo "Step 3: Generating PERTURBED results (rate: $PERTURBATION_RATE)"
echo "=========================================="
echo ""

update_env_perturbation "true" "$PERTURBATION_RATE"

# Clean up old perturbed results if they exist
if [ -d "$PERTURBED_RESULT_DIR" ]; then
    echo "🗑️  Removing old perturbed results..."
    rm -rf "$PERTURBED_RESULT_DIR"
fi

echo "🔄 Generating perturbed results..."
for model in $MODELS; do
    echo "  Generating for $model..."
    bfcl generate \
        --model "$model" \
        --test-category "$TEST_CATEGORY" \
        --num-threads 4 \
        --result-dir "$PERTURBED_RESULT_DIR" \
        --allow-overwrite || {
        echo "❌ Generation failed for $model"
        exit 1
    }
done

echo ""
echo "✅ Perturbed generation complete!"
echo ""

# Step 4: Evaluate PERTURBED results
echo "=========================================="
echo "Step 4: Evaluating PERTURBED results"
echo "=========================================="
echo ""

for model in $MODELS; do
    echo "🦍 Model: $model (perturbed)"
    bfcl evaluate \
        --model "$model" \
        --test-category "$TEST_CATEGORY" \
        --result-dir "$PERTURBED_RESULT_DIR" \
        --score-dir "$PERTURBED_SCORE_DIR" || {
        echo "⚠️  Evaluation failed for $model"
    }
    echo ""
done

echo "✅ Perturbed evaluation complete!"
echo ""

# Step 5: Display comparison
echo "=========================================="
echo "Results Comparison"
echo "=========================================="
echo ""

echo "Unperturbed Results:"
for model in $MODELS; do
    if [ -f "$UNPERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_base_score.json" ]; then
        base_acc=$(python3 -c "import json; f=open('$UNPERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_base_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}%\")" 2>/dev/null || echo "N/A")
        no_snippet_acc=$(python3 -c "import json; f=open('$UNPERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_no_snippet_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}%\")" 2>/dev/null || echo "N/A")
        echo "  $model:"
        echo "    web_search_base: $base_acc"
        echo "    web_search_no_snippet: $no_snippet_acc"
    fi
done

echo ""
echo "Perturbed Results (rate: $PERTURBATION_RATE):"
for model in $MODELS; do
    if [ -f "$PERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_base_score.json" ]; then
        base_acc=$(python3 -c "import json; f=open('$PERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_base_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}%\")" 2>/dev/null || echo "N/A")
        no_snippet_acc=$(python3 -c "import json; f=open('$PERTURBED_SCORE_DIR/$model/agentic/BFCL_v4_web_search_no_snippet_score.json'); d=json.load(f); print(f\"{d['accuracy']*100:.2f}%\")" 2>/dev/null || echo "N/A")
        echo "  $model:"
        echo "    web_search_base: $base_acc"
        echo "    web_search_no_snippet: $no_snippet_acc"
    fi
done

echo ""
echo "=========================================="
echo "✅ All done! Results saved in:"
echo "   - Unperturbed: $UNPERTURBED_RESULT_DIR, $UNPERTURBED_SCORE_DIR"
echo "   - Perturbed: $PERTURBED_RESULT_DIR, $PERTURBED_SCORE_DIR"
echo "=========================================="

